spring:
  profiles:
    active: local
    group:
      local:
        - local-db
        - local-scheduling
      dev:
        - dev-db
    # common
    include:
      - kakao
      - molit
      - vworld
  # default features
  jpa:
    open-in-view: false